name: 'Plone Monorepo: Setup Backend'
description: 'Setup backend codebase of a monorepo project based on Plone'
inputs:
  python-version:
    description: 'Python Version'
    required: true
    default: '3.12'
  plone-version:
    description: 'Plone Version'
    required: true
    default: '6.1.0'
  working-directory:
    description: 'Working directory to use'
    required: false
    default: 'backend'
runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: false

    - name: Restore uv cache
      uses: actions/cache@v4
      working-directory: ${{ inputs.working-directory }}
      with:
        path: ${{ env.UV_CACHE_DIR }}
        key: uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}-${{ hashFiles('pyproject.toml') }}
          uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}

    - name: Install Plone and package
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: make install
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}
        PLONE_VERSION: ${{ inputs.plone-version }}
