name: "Backend: Test Python codebase"

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      plone-version:
        required: true
        type: string
      working-directory:
        required: false
        default: backend
        type: string

jobs:

  coverage:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: ${{ inputs.python-version }}
      PLONE_VERSION: ${{ inputs.plone-version }}
    steps:

        - name: Setup Backend
          uses: ./.github/actions/setup_backend
          with:
            python-version: ${{ inputs.python-version }}
            plone-version: ${{ inputs.plone-version }}
            working-directory: ${{ inputs.working-directory }}

        - name: Run tests
          working-directory: ${{ inputs.working-directory }}
          run: make test-coverage

        - name: Report Coverage
          working-directory: ${{ inputs.working-directory }}
          run: |
            echo "# Coverage Report" >> $GITHUB_STEP_SUMMARY
            echo "$(uv run coverage report --format markdown)" >> $GITHUB_STEP_SUMMARY
