name: "Backend: Test Python codebase"

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      plone-version:
        required: true
        type: string

defaults:
  run:
    working-directory: backend

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: ${{ inputs.python-version }}
      PLONE_VERSION: ${{ inputs.plone-version }}
    steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Backend
          uses: ./.github/actions/setup_backend
          with:
            python-version: ${{ inputs.python-version }}
            plone-version: ${{ inputs.plone-version }}

        - name: Run tests
          run: make test
