name: "Frontend: Check i18n"

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      working-directory:
        required: false
        default: frontend
        type: string

jobs:
  i18n:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Setup Frontend
        uses: kitconcept/meta/.github/actions/setup_frontend@main
        with:
            node-version: ${{ inputs.node-version }}
            working-directory: ${{ inputs.working-directory }}

      - name: i18n
        id: i18n
        working-directory: ${{ inputs.working-directory }}
        run: make ci-i18n
