name: Container Image Generation

on:
  workflow_call:
    inputs:
      base-tag:
        required: true
        type: string
      image-name-prefix:
        required: true
        type: string
      image-name-suffix:
        required: true
        type: string
      platforms:
        required: false
        default: "linux/amd64"
        type: string
      working-directory:
        required: true
        type: string
      dockerfile:
        required: false
        default: Dockerfile
        type: string
      registry:
        required: false
        default: "ghcr.io"
        type: string
      build-args:
        required: false
        default: ""
        type: string
      push:
        required: false
        default: true
        type: boolean
      upload:
        required: false
        default: false
        type: boolean
      upload-name:
        required: false
        default: "image.tar"
        type: string
    secrets:
        username:
            required: true
        password:
            required: true

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ inputs.image-name-prefix }}-${{ inputs.image-name-suffix }}
          labels: |
            org.label-schema.docker.cmd=docker run -d ${{ inputs.image-name-prefix }}-${{ inputs.image-name-suffix }}:${{ inputs.base-tag }}
          flavor:
            latest=false
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context:  ${{ inputs.working-directory }}
          file: ${{ inputs.working-directory }}/${{ inputs.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true
          build-args: ${{ inputs.build-args }}
          outputs: type=docker,dest=${{ runner.temp }}/${{ inputs.upload-name }}

      - name: Publish Image
        if: ${{ inputs.push }}
        uses: docker/build-push-action@v6
        with:
            platforms: ${{ inputs.platforms }}
            context:  ${{ inputs.working-directory }}
            file: ${{ inputs.working-directory }}/${{ inputs.dockerfile }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: ${{ inputs.build-args }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ inputs.upload }}
        with:
          name: ${{ inputs.upload-name }}
          path: ${{ runner.temp }}/${{ inputs.upload-name }}
